// Code generated by ifacemaker; DO NOT EDIT.

package person

// Person ...
type Person interface {
	// SetName set person's name.
	SetName(name string)
	// GetName get person's name.
	GetName() string
}
