// Code generated by ifacemaker; DO NOT EDIT.

package person

//go:generate mockgen -source=Person.go -destination=mocks/Person.go -package=mocks . Person

// Person ...
type Person interface {
	// SetName set person's name.
	SetName(name string)
	// GetName get person's name.
	GetName() string
}
